-- Create tabel users
CREATE TABLE users (
id VARCHAR(30) UNIQUE NOT NULL,
fullname VARCHAR(255) NOT NULL,
nickname VARCHAR(15) NOT NULL,
username VARCHAR(20) UNIQUE NOT NULL,
nohp VARCHAR(15) NOT NULL,
email VARCHAR(255) UNIQUE NOT NULL,
password VARCHAR(255) NOT NULL,
image VARCHAR(255) NOT NULL,
office VARCHAR(50) NOT NULL,
role VARCHAR(30) NOT NULL,
createdAt TIMESTAMP NOT NULL,
updatedAt TIMESTAMP);

-- Create tabel goods
CREATE TABLE goods (
id VARCHAR(30) UNIQUE NOT NULL,
name VARCHAR(255) NOT NULL,
stockmin SMALLINT NOT NULL,
stock SMALLINT NOT NULL,
createdAt TIMESTAMP NOT NULL,
updatedAt TIMESTAMP);